### PR TITLE
181 election day reminder form

### LINKED ISSUE #181: Election Day Reminder Form
election reminder form

This is a form with two inputs (one for telephone, the other for email).  A link that opens the privacy policy in a new tab is provided.  User is able to submit the information or close the form.

### Behavior Rules 
- [ ] User needs to complete at least one input to complete the form.
- [ ] User's input needs to pass validation in all forms that are filled out. (telephone, email)
- [ ] If telephone or email fail validation, display an appropriate error message under the input.
- [ ] If all fields pass validation, submit the data to an endpoint. 
- [ ] On submission success, close the modal.  Flip a flag `contactInfoSubmitted` to true. 
- [ ] On submission error, display an error message in the modal.
- [ ] Clicking cancel clears the inputs and closes the modal.

### PR DESCRIPTION
**Pull request by wbprice**
Fixes #181 and #182

### CODE REVIEW

File: assets/js/redux/survey/survey-actions.js [hunk 1]
```diff
@@ -396,10 +397,172 @@ export function fetchSurveyCandidateMatches(id) {
...
+    errors.alert = {
+      message: 'At least one piece of contact information should be provided',
+      severity: 'warning'
+    }
+    return errors
+  }
+
+  // If errors were found, return the error object.  If not, return undefined.
+  const numberOfErrors = Object.keys(errors).length
+  if (numberOfErrors) {
```
Comment (stanzheng) [inline assets/js/redux/survey/survey-actions.js]: didn't pull this down but could this be simplified to just if (numberOfErrors > 0)?

File: assets/js/redux/survey/survey-actions.js [hunk 2]
```diff
@@ -396,10 +397,172 @@ export function fetchSurveyCandidateMatches(id) {
...
+    validateEmailAddress()
+  }
+
+  // If a telephone number was provided:
+  if (telephone.value) {
+    validateTelephoneNumber()
+  }
+
+  // Nothing is defined.
+  else if (!email.value && !telephone.value) {
```
Comment (stanzheng) [inline assets/js/redux/survey/survey-actions.js]: maybe just if, seems tricky because its not connected to other statement was looking for other clause. 

See what you're doing to short circuit and just attach to line 498 but might be more clear just to check simply.

**Comment by wbprice** [comment]
@stanzheng updated.  When you get a chance, can you clone and try to break it?
